plugin/release: update

diff --git a/plugin/ciel-release b/plugin/ciel-release
--- a/plugin/ciel-release
+++ b/plugin/ciel-release
@@ -4,12 +4,15 @@
 #        which defined in ciel-generate.
 XZ_PARAM="-9 -e --lzma2=preset=9e,nice=273"
 DATE="$(TZ=UTC date +'%Y%m%d')"
-ARCH="$(ciel shell "dpkg-architecture -qDEB_BUILD_ARCH")"
+ciel add __release__
+ARCH="$(ciel shell -i __release__ "dpkg-architecture -qDEB_BUILD_ARCH")"
+ciel del __release__
 VARIANT="$1"
+OS_PATH="$CIEL_DIR/.ciel/container/dist"
+WORKDIR="$PWD"
 
-if [[ ! "$CIEL_INST" ]]; then
-	echo "Please specify an instance via environment variable first."
-	echo "CIEL_INSTANCE=..."
+if [[ ! "$CIEL_DIR" ]]; then
+	echo "\$CIEL_DIR cannot be null."
 	exit 127
 fi
 
@@ -17,13 +20,13 @@ if [[ ! "$TARBALL" ]]; then
 	TARBALL=aosc-os_${VARIANT}_"${DATE}"_"${ARCH}".tar.xz
 fi
 
-pushd "$CIEL_INST" || exit $?
+pushd "$OS_PATH" || exit $?
 
 _ciel_tarball() {
 	# Make a tarball
-	tar cvf - * | $COMPRESSOR > ../"$TARBALL" || exit $?
+	tar cvf - * | $COMPRESSOR > "$WORKDIR/$TARBALL" || exit $?
 	# Generate SHA256 checksum.
-	sha256sum ../"$TARBALL" > ../"$TARBALL".sha256sum || exit $?
+	sha256sum "$WORKDIR/$TARBALL" > "$WORKDIR/$TARBALL".sha256sum || exit $?
 }
 
 if [[ ! "$COMPRESSOR" ]]; then
